// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCondition) DeepCopyInto(out *ClusterCondition) {
	*out = *in
	out.Message = in.Message
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCondition.
func (in *ClusterCondition) DeepCopy() *ClusterCondition {
	if in == nil {
		return nil
	}
	out := new(ClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRCluster) DeepCopyInto(out *DRCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRCluster.
func (in *DRCluster) DeepCopy() *DRCluster {
	if in == nil {
		return nil
	}
	out := new(DRCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DRCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRClusterList) DeepCopyInto(out *DRClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DRCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRClusterList.
func (in *DRClusterList) DeepCopy() *DRClusterList {
	if in == nil {
		return nil
	}
	out := new(DRClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DRClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRClusterSpec) DeepCopyInto(out *DRClusterSpec) {
	*out = *in
	out.DRComponents = in.DRComponents
	in.PairClusterSettings.DeepCopyInto(&out.PairClusterSettings)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRClusterSpec.
func (in *DRClusterSpec) DeepCopy() *DRClusterSpec {
	if in == nil {
		return nil
	}
	out := new(DRClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRClusterStatus) DeepCopyInto(out *DRClusterStatus) {
	*out = *in
	out.DRComponents = in.DRComponents
	if in.ClusterConditions != nil {
		in, out := &in.ClusterConditions, &out.ClusterConditions
		*out = make([]*ClusterCondition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ClusterCondition)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRClusterStatus.
func (in *DRClusterStatus) DeepCopy() *DRClusterStatus {
	if in == nil {
		return nil
	}
	out := new(DRClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRComponents) DeepCopyInto(out *DRComponents) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRComponents.
func (in *DRComponents) DeepCopy() *DRComponents {
	if in == nil {
		return nil
	}
	out := new(DRComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRFilterConfig) DeepCopyInto(out *DRFilterConfig) {
	*out = *in
	if in.VariableDeleteFilter != nil {
		in, out := &in.VariableDeleteFilter, &out.VariableDeleteFilter
		*out = new(VariableDeleteFilterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.VariableMappingFilter != nil {
		in, out := &in.VariableMappingFilter, &out.VariableMappingFilter
		*out = new(VariableMappingFilterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.WhiteListFilter != nil {
		in, out := &in.WhiteListFilter, &out.WhiteListFilter
		*out = new(WhiteListFilterConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRFilterConfig.
func (in *DRFilterConfig) DeepCopy() *DRFilterConfig {
	if in == nil {
		return nil
	}
	out := new(DRFilterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRNamespace) DeepCopyInto(out *DRNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRNamespace.
func (in *DRNamespace) DeepCopy() *DRNamespace {
	if in == nil {
		return nil
	}
	out := new(DRNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DRNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRNamespaceList) DeepCopyInto(out *DRNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DRNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRNamespaceList.
func (in *DRNamespaceList) DeepCopy() *DRNamespaceList {
	if in == nil {
		return nil
	}
	out := new(DRNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DRNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRNamespaceSpec) DeepCopyInto(out *DRNamespaceSpec) {
	*out = *in
	out.DRComponents = in.DRComponents
	in.DRFilterConfig.DeepCopyInto(&out.DRFilterConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRNamespaceSpec.
func (in *DRNamespaceSpec) DeepCopy() *DRNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(DRNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRNamespaceStatus) DeepCopyInto(out *DRNamespaceStatus) {
	*out = *in
	out.DRComponents = in.DRComponents
	in.DRFilterConfig.DeepCopyInto(&out.DRFilterConfig)
	if in.SyncedConditions != nil {
		in, out := &in.SyncedConditions, &out.SyncedConditions
		*out = make(map[string]SyncedCondition, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRNamespaceStatus.
func (in *DRNamespaceStatus) DeepCopy() *DRNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(DRNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupVersionKind) DeepCopyInto(out *GroupVersionKind) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupVersionKind.
func (in *GroupVersionKind) DeepCopy() *GroupVersionKind {
	if in == nil {
		return nil
	}
	out := new(GroupVersionKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupVersionKindObject) DeepCopyInto(out *GroupVersionKindObject) {
	*out = *in
	out.GroupVersionKind = in.GroupVersionKind
	out.ObjectKey = in.ObjectKey
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupVersionKindObject.
func (in *GroupVersionKindObject) DeepCopy() *GroupVersionKindObject {
	if in == nil {
		return nil
	}
	out := new(GroupVersionKindObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupVersionResource) DeepCopyInto(out *GroupVersionResource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupVersionResource.
func (in *GroupVersionResource) DeepCopy() *GroupVersionResource {
	if in == nil {
		return nil
	}
	out := new(GroupVersionResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPTransportorSetting) DeepCopyInto(out *HTTPTransportorSetting) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPTransportorSetting.
func (in *HTTPTransportorSetting) DeepCopy() *HTTPTransportorSetting {
	if in == nil {
		return nil
	}
	out := new(HTTPTransportorSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeApiServerSettings) DeepCopyInto(out *KubeApiServerSettings) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeApiServerSettings.
func (in *KubeApiServerSettings) DeepCopy() *KubeApiServerSettings {
	if in == nil {
		return nil
	}
	out := new(KubeApiServerSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Message) DeepCopyInto(out *Message) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Message.
func (in *Message) DeepCopy() *Message {
	if in == nil {
		return nil
	}
	out := new(Message)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamesapceCRStatus) DeepCopyInto(out *NamesapceCRStatus) {
	*out = *in
	out.ObjectKey = in.ObjectKey
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamesapceCRStatus.
func (in *NamesapceCRStatus) DeepCopy() *NamesapceCRStatus {
	if in == nil {
		return nil
	}
	out := new(NamesapceCRStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjResource) DeepCopyInto(out *ObjResource) {
	*out = *in
	if in.Unstructured != nil {
		in, out := &in.Unstructured, &out.Unstructured
		*out = (*in).DeepCopy()
	}
	if in.GVR != nil {
		in, out := &in.GVR, &out.GVR
		*out = new(schema.GroupVersionResource)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjResource.
func (in *ObjResource) DeepCopy() *ObjResource {
	if in == nil {
		return nil
	}
	out := new(ObjResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectKey) DeepCopyInto(out *ObjectKey) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectKey.
func (in *ObjectKey) DeepCopy() *ObjectKey {
	if in == nil {
		return nil
	}
	out := new(ObjectKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PairClusterSettings) DeepCopyInto(out *PairClusterSettings) {
	*out = *in
	if in.KubeApiserverTransportorSetting != nil {
		in, out := &in.KubeApiserverTransportorSetting, &out.KubeApiserverTransportorSetting
		*out = new(KubeApiServerSettings)
		**out = **in
	}
	if in.HTTPTransportorSetting != nil {
		in, out := &in.HTTPTransportorSetting, &out.HTTPTransportorSetting
		*out = new(HTTPTransportorSetting)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PairClusterSettings.
func (in *PairClusterSettings) DeepCopy() *PairClusterSettings {
	if in == nil {
		return nil
	}
	out := new(PairClusterSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncedCondition) DeepCopyInto(out *SyncedCondition) {
	*out = *in
	out.GroupVersionKindObject = in.GroupVersionKindObject
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncedCondition.
func (in *SyncedCondition) DeepCopy() *SyncedCondition {
	if in == nil {
		return nil
	}
	out := new(SyncedCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableDelete) DeepCopyInto(out *VariableDelete) {
	*out = *in
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(GroupVersionKindObject)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(GroupVersionKind)
		**out = **in
	}
	if in.KeyValueDelete != nil {
		in, out := &in.KeyValueDelete, &out.KeyValueDelete
		*out = make([]VariableKey, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableDelete.
func (in *VariableDelete) DeepCopy() *VariableDelete {
	if in == nil {
		return nil
	}
	out := new(VariableDelete)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableDeleteFilterConfig) DeepCopyInto(out *VariableDeleteFilterConfig) {
	*out = *in
	if in.ObjectDeleteList != nil {
		in, out := &in.ObjectDeleteList, &out.ObjectDeleteList
		*out = make([]VariableDelete, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KindDeleteList != nil {
		in, out := &in.KindDeleteList, &out.KindDeleteList
		*out = make([]VariableDelete, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableDeleteFilterConfig.
func (in *VariableDeleteFilterConfig) DeepCopy() *VariableDeleteFilterConfig {
	if in == nil {
		return nil
	}
	out := new(VariableDeleteFilterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableMapping) DeepCopyInto(out *VariableMapping) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableMapping.
func (in *VariableMapping) DeepCopy() *VariableMapping {
	if in == nil {
		return nil
	}
	out := new(VariableMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableMappingFilterConfig) DeepCopyInto(out *VariableMappingFilterConfig) {
	*out = *in
	if in.ObjectVariableMappings != nil {
		in, out := &in.ObjectVariableMappings, &out.ObjectVariableMappings
		*out = make([]VariableMappings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KindVariableMappings != nil {
		in, out := &in.KindVariableMappings, &out.KindVariableMappings
		*out = make([]VariableMappings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableMappingFilterConfig.
func (in *VariableMappingFilterConfig) DeepCopy() *VariableMappingFilterConfig {
	if in == nil {
		return nil
	}
	out := new(VariableMappingFilterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableMappings) DeepCopyInto(out *VariableMappings) {
	*out = *in
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(GroupVersionKindObject)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(GroupVersionKind)
		**out = **in
	}
	if in.KeyValueMappings != nil {
		in, out := &in.KeyValueMappings, &out.KeyValueMappings
		*out = make(map[VariableKey]VariableMapping, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableMappings.
func (in *VariableMappings) DeepCopy() *VariableMappings {
	if in == nil {
		return nil
	}
	out := new(VariableMappings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WhiteListFilterConfig) DeepCopyInto(out *WhiteListFilterConfig) {
	*out = *in
	if in.ObjectWhiteList != nil {
		in, out := &in.ObjectWhiteList, &out.ObjectWhiteList
		*out = make([]GroupVersionKindObject, len(*in))
		copy(*out, *in)
	}
	if in.KindWhiteList != nil {
		in, out := &in.KindWhiteList, &out.KindWhiteList
		*out = make([]GroupVersionKind, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WhiteListFilterConfig.
func (in *WhiteListFilterConfig) DeepCopy() *WhiteListFilterConfig {
	if in == nil {
		return nil
	}
	out := new(WhiteListFilterConfig)
	in.DeepCopyInto(out)
	return out
}
